apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysite
  namespace: {{ .Release.Namespace | quote }}
spec:
  capacity:
    storage: 2Gi
  hostPath:
    path: /code/storage/mysite
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: {{ .Release.Namespace | quote }}
    name: mysite
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysite
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: mysite
  storageClassName: local-path
  volumeMode: Filesystem